#!/bin/bash

./clean
mkdir -p target/tables
mkdir -p target/packages
mkdir -p target/package_bodies


for i in $(seq 1 $1)
do
  columns=$(( ( RANDOM % 10  )  + 1  ))
  procedures=$(( ( RANDOM % 3  )  + 1  ))
  ./src/create-table table_$i $columns
  ./src/create-package package_$i procedure $procedures
  ./src/create-package-body package_$i procedure $procedures
done
#
# for dir in target/*
# do
#   for i in $(seq 1 $2)
#   do
#     echo "Implementing features from SUBEFFORT-$i" > $dir/file$i
#   done
# done
