#!/bin/bash

target=./target/package_bodies/$1

name=$1
procedure=$2
data=""
execute=""
for i in $(seq 1 $3)
do
  data+="\n  PROCEDURE $procedure\_$i\n  IS\n    ${procedure:0:1}$i VARCHAR2 (32) := 'Hello procedure\_$i';\n  BEGIN\n    DBMS_OUTPUT.put_line (${procedure:0:1}$i);\n  END $procedure\_$i;\n"
done

execute+="begin\n"
for i in $(seq 1 $3)
do
  execute+="  $name.$procedure\_$i;\n"
done
execute+="end;\n"

touch $target
sed -e "s/\${name}/$name/" -e "s/\${data}/$data/" -e "s/\${execute}/$execute/" src/templates/package-body > $target

