#!/bin/bash

target=./target/packages/$1

name=$1
procedure=$2
data=""

for i in $(seq 1 $3)
do
  data+="  PROCEDURE $procedure\_$i;\n"
done

touch $target
sed -e "s/\${name}/$name/" -e "s/\${data}/$data/" src/templates/package > $target
